In [1]:
import numpy as np

In [2]:
# Basic Operations of Array

a = np.array([1, 2, 3, 4])
a 

array([1, 2, 3, 4])

In [3]:
a + 1

array([2, 3, 4, 5])

In [4]:
a ** 2

array([ 1,  4,  9, 16])

In [5]:
b = np.ones(4)
b

array([1., 1., 1., 1.])

In [6]:
b + 1

array([2., 2., 2., 2.])

In [7]:
a

array([1, 2, 3, 4])

In [8]:
b

array([1., 1., 1., 1.])

In [9]:
a - b

array([0., 1., 2., 3.])

In [10]:
a * b 

array([1., 2., 3., 4.])

In [11]:
# Matrix Multiplication

c = np.diag([1, 2, 3, 4]) 
c

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [12]:
c * c 

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [13]:
c.dot(c)

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [14]:
# Comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])

In [15]:
a == b 

array([False,  True, False,  True])

In [16]:
a > b 

array([False, False,  True, False])

In [17]:
# array-wise comparisons

a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [18]:
np.array_equal(a, b)

False

In [19]:
np.array_equal(a, c)

True

In [20]:
# Logical Operations
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

In [21]:
np.logical_or(a, b)

array([ True,  True,  True, False])

In [22]:
np.logical_and(a, b)

array([ True, False, False, False])

In [23]:
# Transcendental functions

a = np.arange(5)

In [24]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [25]:
a

array([0, 1, 2, 3, 4])

In [26]:
np.log(a)

/var/folders/3b/ly9h8hy931j_x7b1h6dbr1wc0000gn/T/ipykernel_21039/176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [27]:
np.exp(a) # evaluates e^x 

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [28]:
# shape Mismatch 

a = np.arange(4)

a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [ ]:
# Basic Reductions

In [29]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [30]:
# Sum by rows and by columns

x = np.array([[1, 1], [2,2]])
x

array([[1, 1],
       [2, 2]])

In [31]:
x.sum(axis=0)

array([3, 3])

In [32]:
x.sum(axis=1)

array([2, 4])

In [33]:
# Other reductions
x = np.array([1, 3, 2])
x.min()

1

In [34]:
x.max()

3

In [35]:
x.argmin() # index of minimum element

0

In [36]:
x.argmax() # index of maximum element

1

In [37]:
# Logical Operations
np.all([True, True, False])

False

In [38]:
np.all([True, True, True])

True

In [39]:
np.any([True, False, False])

True

In [40]:
a = np.zeros((50,50))
np.any(a != 0)

False

In [41]:
np.all(a == a)

True

In [42]:
np.all(a == 0)

True

In [43]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [44]:
((a <= b) & (b <= c)).all()

True

In [45]:
# Statistics

x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])

In [46]:
x.mean()

1.75

In [48]:
np.median(x)

1.5

In [49]:
np.median(y, axis = 1)

array([2., 5.])

In [50]:
np.median(y, axis = -1) # last axis

array([2., 5.])

In [51]:
np.median(y, axis = 0)

array([3., 4., 2.])

In [52]:
x.std()

0.82915619758885